concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v2
      with:
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gt-maven-

          '
    - continue-on-error: true
      name: Disable checksum offloading
      run: 'sudo ethtool -K eth0 tx off rx off

        '
    - continue-on-error: true
      name: Build GeoTools (no tests, prepare fresh artifacts)
      run: 'mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        clean install -T2 -Dall --file pom.xml -DskipTests

        '
    - continue-on-error: true
      name: Checkout GeoWebCache, GeoServer and ...
      run: 'cd ~

        echo "Preparing git ssh checkouts"

        mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >
        ~/.ssh/config

        echo "Checking out GeoWebCache"

        mkdir geowebcache

        git clone https://github.com/GeoWebCache/geowebcache.git geowebcache

        echo "Checking out GeoServer"

        mkdir geoserver

        git clone https://github.com/geoserver/geoserver.git geoserver

        echo "Checking out mapfish-print-v2"

        mkdir mapfish-print-v2

        git clone https://github.com/mapfish/mapfish-print-v2.git mapfish-print-v2

        '
    - continue-on-error: true
      name: Build Mapfish-print v2 with tests
      run: 'cd ~

        mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -f mapfish-print-v2/pom.xml install -nsu -DskipTests -T2

        mvn -B -f mapfish-print-v2/pom.xml test -fae -nsu -T2

        '
    - continue-on-error: true
      name: Build GeoWebCache with tests
      run: 'export TEST_OPTS="-XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30
        -XX:MinHeapFreeRatio=10"

        export MAVEN_OPTS="-Xmx1024m $TEST_OPTS"

        cd ~

        mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -f geowebcache/geowebcache/pom.xml install -nsu -Dspotless.apply.skip=true
        -DskipTests -T2

        mvn -B -f geowebcache/geowebcache/pom.xml test -fae -nsu -T2 -Dspotless.apply.skip=true

        '
    - continue-on-error: true
      name: Build GeoServer with tests
      run: 'echo "Building GeoServer"

        export TEST_OPTS="-XX:+UseStringDeduplication -XX:+UseG1GC -XX:MaxHeapFreeRatio=30
        -XX:MinHeapFreeRatio=10"

        export MAVEN_OPTS="-Xmx512m $TEST_OPTS"

        cd ~

        sed -i "s/<mf.version>2.2.0<\/mf.version>/<mf.version>2.3-SNAPSHOT<\/mf.version>/g"
        geoserver/src/pom.xml

        sed -i "s/<gf.version>3.6.0<\/gf.version>/<gf.version>3.6-SNAPSHOT<\/gf.version>/g"
        geoserver/src/pom.xml

        mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -f geoserver/src/pom.xml install -nsu -Prelease -Dspotless.apply.skip=true
        -DskipTests -T2

        mvn -B -f geoserver/src/community/pom.xml install -nsu -DcommunityRelease
        -Dspotless.apply.skip=true -DskipTests -T2

        mvn -B -f geoserver/src/pom.xml test -fae -T2 -nsu -Dtest.maxHeapSize=512m
        -Djvm.opts="$TEST_OPTS" -Prelease -Dspotless.apply.skip=true

        '
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
name: Downstream integration build (GeoWebCache and GeoServer)
on:
  repository_dispatch:
    types: trigger-ga___integration.yml
