concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Setup python for docs
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: 3.x
    - continue-on-error: true
      name: Setup python pip requirements for building docs
      run: 'pip install -r requirements.txt

        '
      working-directory: docs
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v2
      with:
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gt-maven-

          '
    - continue-on-error: true
      name: Disable checksum offloading
      run: sudo ethtool -K eth0 tx off rx off
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn -B clean install -Dspotless.apply.skip=true -Dall -T2 -U -Plinux-github-build
        --file pom.xml

        '
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: 'find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

        '
name: Linux JDK 21 GitHub CI
on:
  repository_dispatch:
    types: trigger-ga___linux_jdk21.yml
