concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v1
      with:
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gt-maven-

          '
    - continue-on-error: true
      name: Disable network offloading
      run: 'sudo sysctl -w net.link.generic.system.hwcksum_tx=0

        sudo sysctl -w net.link.generic.system.hwcksum_rx=0

        '
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean install -T2 -Dall --file pom.xml -Dspotless.apply.skip=true
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: 'find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

        '
name: Mac OS CI
on:
  repository_dispatch:
    types: trigger-ga___macos.yml
