concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    name: MS SQL ${{ matrix.mssql }} online test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v3
      with:
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gt-maven-

          '
    - continue-on-error: true
      name: Setup test environment for MS SQL ${{ matrix.mssql }}
      run: './build/ci/mssql/start-mssql.sh ${{ matrix.mssql }}

        ./build/ci/mssql/setup-mssql.sh

        '
    - continue-on-error: true
      name: Build GeoTools dependent modules (no tests)
      run: mvn -B clean install -T2 -Dall -pl :gt-jdbc-sqlserver -DskipTests -Dspotless.apply.skip=true
        -am
    - continue-on-error: true
      name: Test MS SQL Server data store
      run: mvn -B clean install -T2 -Dall -pl :gt-jdbc-sqlserver -Ponline -Dspotless.apply.skip=true
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: 'find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

        '
    strategy:
      matrix:
        java:
        - 11
        mssql:
        - 2019-latest
        - 2022-latest
name: MS SQL Server online tests
on:
  repository_dispatch:
    types: trigger-ga___mssql_online.yml
