concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v2
      with:
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gt-maven-

          '
    - continue-on-error: true
      name: Disable network offloading
      run: Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn --% -B clean install -Dall -T2 --file pom.xml -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS

        '
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: 'cmd --% /c for /f %i in (''dir /a:d /s /b %userprofile%\*SNAPSHOT*'')
        do rd /s /q %i

        '
name: Windows GitHub CI
on:
  repository_dispatch:
    types: trigger-ga___windows.yml
